name: Deploy

on:
  push:
    branches:
      - 'main'

concurrency: docker-hub

jobs:
  push-docker-hub:
    name: docker build and push to docker hub
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_SECRET }}

      - name: Docker build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: cyppan/sample-webservice:${{ github.sha }}

  deploy-aws:
    needs: push-docker-hub
    name: Deploy the docker image to the ECS service
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "eu-north-1"

      - name: Update image tag in task definition file
        id: update-task-definition
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: my-container
          image: cyppan/sample-webservice:${{ github.sha }}
      
      - name: Deploy to AWS ECS my-service
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.update-task-definition.outputs.task-definition }}
          service: my-service
          cluster: my-cluster
